language: php
php:
    - "7.4snapshot"
    - "7.3"
    - "7.2"

matrix:
    fast_finish: true

install:
    - composer install --no-interaction --no-progress

script:
    - bin/phpunit

notifications:
    email: false
    webhooks:
        - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always
